### ISSUE TITLE
Migration from API v1 to v2.0.0

### ISSUE THREAD

**Issue by godismyjudge95** [brpaz/ulauncher-statuspages#2]
Ulauncher just released a new version and it broke this extension.
See here:
https://mailchi.mp/fbb4b54c426a/ulauncher-is-migrating-to-python-3-changes-to-extension-api-and-more

And here:
http://docs.ulauncher.io/en/latest/extensions/migration.html

**Comment by brpaz** [comment]
The extension already works with Ulauncher V5
